title: Sam's homepage
logo: images/Grad Pic.JPG
description: Bookmark this page to see what I'm wroking on!

www.linkedin.com/in/samuel-volpone
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
